name: Mirror to GitLab
on: [push]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures a full clone, not shallow

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.liu.se/hicko047/TDDD27_2025_PlanPilotpp.git
          git push --all gitlab
          git push --tags gitlab

